### ISSUE TITLE
Is this project being worked on?

### ISSUE THREAD

**Issue by shaunek** [flauberjp/intellij-peacock#1]
I came across this repo on google when I searched "intellij peacock" - I was searching for a plugin for Intellij that provides the functionality of the VSCode Peacock plugin. Just curious if this project was intended to be such a project and if so, do you have plans to work on it? It would definitely be pretty nice.

**Comment by MadeleineSmith** [comment]
Amen, this would be super useful 👍

**Comment by flauberjp** [comment]
no plans from my side, guys! 
I remember to workaround it by using other project.
Doing a quick search, I found this one: https://github.com/nowtilous/Project-Color
In theory it should work.
